use_modular_headers!

# Load react_native_pods.rb with the proper path
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.4' # Set a compatible iOS version

# Enable Frameworks if specified
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'APP' do
  # Properly initialize the `config` variable
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Test targets (if any)
  target 'APPTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  # React Native post-install hook
  react_native_post_install(installer)

  # gRPC-C++ compatibility fix
  installer.pods_project.targets.each do |target|
    if target.name.include?('gRPC-C++')
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator]'] = 'arm64'
      end
    end
  end
end

